### ISSUE TITLE
adding header 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by kfe908** [chrislusf/seaweedfs#1271]
Could you please include the feature adding individual headers like 'Access-Control-Allow-Origin' for responses? Otherwise, like many users (sea Google search) we have to use nginx or apache in front of seaweedfs. That slows the great speed of seaweedfs down and eats unnecessary resources .

In the meantime, where do we find this "response part" in the source code, so we would manually add this part and rebuild everything?

Thanks

**Comment by chrislusf** [comment]
Add `Access-Control-Allow-Origin: *` to all requests?

**Comment by kfe908** [comment]
Yes, to all responses, e. g. add header(s) via command line and seafeedfs would include that header when serving images/data.

We have a bunch of servers via sub domains serving a ton of images. Sub domains are treated as separated domains and we have a new use case/feature set where seaweedfs will not work due to CORS policy.

We can include it manually and rebuild seaweedfs again though. But where?

**Comment by chrislusf** [comment]
Assuming you are using volume servers, add the fix similar to this line: https://github.com/chrislusf/seaweedfs/blob/fee3319cbf4ed88f79c6e7fe19bada2bddabbb85/weed/server/volume_server_handlers_read.go#L246

**Comment by glowkeeper** [comment]
I've just started using Filer. Looks great, but I'm getting a CORS error using the javascript `Fetch` API: 

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8888/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

Part of the reason I've gone for SeaweedFS is the ease of setup, so I'd like to avoid having to put a webserver in front of it all. Was a fix added? 

ps. I do this on one of my `go` REST servers (using `github.com/gorilla/handlers`):

```
cors := handlers.CORS(
        handlers.AllowedHeaders([]string{"content-type"}),
        handlers.AllowedMethods([]string{"GET"}),
        handlers.AllowedOrigins([]string{"*"}),
        handlers.AllowCredentials(),
    )
```

**Comment by chrislusf** [comment]
@glowkeeper you want to add this to the filers, not volume servers, correct?

How about just doing this:

* add Access-Control-Allow-Origin: * to all requests that has a "Origin" header.

**Comment by glowkeeper** [comment]
Indeed (filers) - that sounds perfect - but forgive me, I'm new to Seaweed
- how do I do that?

**Comment by chrislusf** [comment]
I added CORS support for filer and volume in 306062b4e7cacf9fbeae227965eeeef08ccfeb92 and 05acc3329411d50e62a973cb9e93edfa7216995f

**Comment by glowkeeper** [comment]
> I added CORS support for filer and volume in 306062b and 05acc33

Great. So how do I enable `Access-Control-Allow-Origin: *` on filer? Forgive me - but I haven't tracked down (yet) any docs related to it  - is that something I can add to `filer.toml` (for example)?

**Comment by chrislusf** [comment]
It is hard coded. Use nginx if customization is needed.

**Comment by glowkeeper** [comment]
I'm confused! Does `filer` enable `Access-Control-Allow-Origin: *`, or not? My experience, so far, is it doesn't (obvs). But then, how was CORS support enabled? 

Anyway - here's my requirement:

1. Currently, I'm trying to access `filer` on `http://localhost:8888/` from some javascript running on `http://localhost:9004/subDomain`. 
2. Ultimately, I'd like to access `filer` on  `http://my.server.org:8888/` from a script running on `http://possibly.anywhere.net:9004/subDomain`.

I'm bypassing CORS errors with  1) by using [local cors proxy](https://github.com/garmeeh/local-cors-proxy).

However, like the original poster, I want to avoid having to proxy `filer` for scenario 2) because I want to keep things as simple as possible for a possibly large set of users who may use my javascript app' for _their own_ `filer` setups.

Is it possible to enable `Access-Control-Allow-Origin` as a configurable option in `filer.toml`? 

(ps. maybe re-open the issue?)

**Comment by chrislusf** [comment]
> Does `filer` enable `Access-Control-Allow-Origin: *`, or not?

Yes. I added CORS support for filer and volume in 306062b and 05acc33, which hard coded "*".

**Comment by glowkeeper** [comment]
So why do I get CORS errors, then?

**Comment by chrislusf** [comment]
> So why do I get CORS errors, then?

Very likely the version you are using does not have the fixes. If not, create an issue with details on how to reproduce it.

**Comment by jareks** [comment]
I am also not getting CORS headers and therefore can't use seaweedfs :/

Here are steps to replicate:

```
$ docker run -p 8333:8333 --rm chrislusf/seaweedfs version
version 30GB 2.68 96514f0f00f1ca6f0f253c1c4080a45887d09ad9 linux amd64

$ docker run -p 8333:8333 --rm chrislusf/seaweedfs server -s3
(...)
 s3.go:201] Start Seaweed S3 API Server 30GB 2.68 96514f0f00f1ca6f0f253c1c4080a45887d09ad9 at http port 8333
 
$ curl  -H 'Origin: http://something' localhost:8333 --verbose
*   Trying 127.0.0.1:8333...
* Connected to localhost (127.0.0.1) port 8333 (#0)
> GET / HTTP/1.1
> Host: localhost:8333
> User-Agent: curl/7.74.0
> Accept: */*
> Origin: http://something
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 206
< Content-Type: application/xml
< Server: SeaweedFS S3 30GB 2.68
< X-Amz-Request-Id: 1635684778631633576
< Date: Sun, 31 Oct 2021 12:52:58 GMT
< 
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host localhost left intact
<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><DisplayName></DisplayName><ID></ID></Owner><Buckets></Buckets></ListAllMyBucketsResult>

# Notice no Access-Control-Allow-* headers
```

Any help would be greatly appreciated!

**Comment by chrislusf** [comment]
@jareks You are listing all buckets. Is this supposed to work? 

Getting each object works.

```
$ curl -v -H 'Origin: http://something' "http://localhost:8333/harbor/docker/registry/v2/repositories/chrislusf/seaweed_agent/_uploads/63de3955-8ba3-4814-8312-bec6d1f8c8a3/hashstates/sha256/12278234" --output -
*   Trying ::1:8333...
* Connected to localhost (::1) port 8333 (#0)
> GET /harbor/docker/registry/v2/repositories/chrislusf/seaweed_agent/_uploads/63de3955-8ba3-4814-8312-bec6d1f8c8a3/hashstates/sha256/12278234 HTTP/1.1
> Host: localhost:8333
> User-Agent: curl/7.77.0
> Accept: */*
> Origin: http://something
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Content-Disposition
< Content-Disposition: inline; filename="12278234"
< Content-Length: 108
< Content-Type: application/octet-stream
< Date: Sun, 31 Oct 2021 17:03:33 GMT
< Etag: "da75852f48c2ddf9e632550bac2f5cb4"
< Last-Modified: Fri, 29 Oct 2021 21:10:31 GMT
< Server: SeaweedFS Filer 30GB 2.75
< X-Amz-Storage-Class: STANDARD
```

**Comment by jareks** [comment]
@chrislusf many thanks for such a quick response!

Indeed, the real problem is not with getting list of all buckets, but with uploading files from browser:
POST http://host/bucket-name/
Content-Type: multipart/form-data

Very simplified example (which results in error - but still no CORS headers, so browser wont report that to javascript):
```
$ curl -F a=b -H 'Origin: http://sometething' 10.152.183.195:9000/bucket --verbose
*   Trying 10.152.183.195:9000...
* Connected to 10.152.183.195 (10.152.183.195) port 9000 (#0)
> POST /bucket HTTP/1.1
> Host: 10.152.183.195:9000
> User-Agent: curl/7.74.0
> Accept: */*
> Origin: htething
> Content-Length: 137
> Content-Type: multipart/form-data; boundary=------------------------84bd241c5ea20644
> 
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Accept-Ranges: bytes
< Content-Length: 226
< Content-Type: application/xml
< Server: SeaweedFS S3 30GB 2.68
< X-Amz-Request-Id: 1635703620667861319
< Date: Sun, 31 Oct 2021 18:07:00 GMT
< 
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host 10.152.183.195 left intact
<Error><Code>MissingFields</Code><Message>Missing fields in request.</Message><Resource>/bucket</Resource><RequestId>1635703620667848530</RequestId><BucketName>bucket</BucketName></Error>
```

Maybe it's simply this endpoint for POSTing file that's not adding CORS headers?

**Comment by chrislusf** [comment]
what about normal successful requests?

**Comment by jareks** [comment]
Same thing, browser reports missing CORS.
It only works fine if I add `Access-Control-Allow-Origin` through my proxy (traefik).

**Comment by akatsukilelouch** [comment]
S3 server doesn't add CORS headers for `OPTIONS` request with seaweedfs `version 30GB 3.97 76452ab59 linux arm64` therefore can't use S3 from browsers right away and some reverse proxy is needed.

though it is true that such proxy is likely mandatory in production but in my development and testing environment this indeed kind of unwieldy.

**Comment by chrislusf** [comment]
@akatsukilelouch is this still an issue? Also check https://github.com/seaweedfs/seaweedfs/wiki/S3-CORS

**Comment by lava** [comment]
@chrislusf I also spent some time investigating CORS issues with seaweed today and can confirm that for 3.99 the default `*` CORS headers only appear for "global" requests to the S3 API, but not for `OPTIONS` or `GET` requests to invidual objects in a bucket.

The situation in general is pretty confusing because there's three separate ways to provide CORS-related configuration:

 * The `security.toml` file which is essentially ignored completely by the S3 component (because the implicit default `*` value of the CLI argument is always preferred)
 * The `-s3.allowedOrigins` parameter which is only used for "global" routes, but not for the `PUT` and `GET` requests to the objects themselves
 * The bucket-level CORS configuration which sets the correct header on the object responses, which cannot be set by config or the `weed shell` but needs an  `aws s3api put-bucket-cors` invocation

The last part works, but is a bit of a pain to set up in an automated way, e.g. a docker compose setup, since the `aws` invocation requires the server to be up and running before it can succeed.

My naive assumption would have been that if there's no bucket-level configuration, then requests fall back to the global CORS settings from the `s3.allowedOrigins` argument, and if that's also not provided fall back further to the settings from the config file.

**Comment by chrislusf** [comment]
@lava thanks for the details! Added a PR https://github.com/seaweedfs/seaweedfs/pull/7404 to address this.
