### ISSUE TITLE
1.79: "topics/.system/log" appears in the root of the FUSE mount

### ISSUE THREAD

**Issue by onlyjob** [chrislusf/seaweedfs#1325]
SeaweedFS creates "topics/.system/log" in the root of the FUSE mount.
IMHO it is not great when file system maintains metadata within the file system.
I recommend to remove "topics" directory. Thanks.

**Comment by chrislusf** [comment]
It's metadata logs for external program to use, e.g., replication, inotify,
async metadata synchronization.

Currently this is the only place to make it scalable.

**Comment by ignusws** [comment]
> 
> It's metadata logs for external program to use, e.g., replication, inotify, async metadata synchronization. Currently this is the only place to make it scalable.

What is retention policy for these logs? is it safe to delete them? is there an opt-out option if this feature not needed right now?
Can you provide a link for detailed description how to use this feature?

**Comment by chrislusf** [comment]
Added here: https://github.com/chrislusf/seaweedfs/wiki/Filer-Metadata-Events

Let me know any suggestions, questions.

**Comment by onlyjob** [comment]
Thanks. Since it is a low-level technical metadata, IMHO it would be better to keep it in a hidden top-level folder (e.g. `.topics`).

**Comment by chrislusf** [comment]
There will be more topics, similar to Kafka.

**Comment by ignusws** [comment]
> Added here: https://github.com/chrislusf/seaweedfs/wiki/Filer-Metadata-Events
> Let me know any suggestions, questions.

Thanks. Snapshots and possible file recovery would be useful. 
How replication level and volumes is chosen for writing this logs? if we have some collections and simple volumes with different level of replication to where this log files will be written?

> Thanks. Since it is a low-level technical metadata, IMHO it would be better to keep it in a hidden top-level folder (e.g. `.topics`).
I do agree here. This kind of data should be separated from other files.
Maybe add some kind of flag to filer and fuse mount, that reveal such folder otherwise don't show this folder at all?

**Comment by chrislusf** [comment]
It uses the filer's default replication and default collection.
