### ISSUE TITLE
Resumable upload/download

### ISSUE THREAD

**Issue by marxxx** [chrislusf/seaweedfs#147]
Is it possible to add resumable file uploads/downloads?
http://www.grid.net.ru/nginx/resumable_uploads.en.html

Or partial file updates/reads so you can read/update part of file:
start=244345&length=34356

It would help alot with big files so it will be possible to store files directly to seaweedfs without first writing file to filesystem and adds resumable upload/download feature..

**Comment by chrislusf** [comment]
It can be better handled on the client side.

In "weed upload" and "weed download" function, a large file can be uploaded and downloaded in segments.

Let me know your use case and see whether it can help you.

**Comment by marxxx** [comment]
Ok, but how can I use this feature with external language like PHP/NodeJS? I want to build cloud service ontop of seaweed. For this I need feature where I can pause/resume upload/download when ever I need.

**Comment by chrislusf** [comment]
Need to know your use case. Most cases you just update the whole file.

Download already supports range request.

**Comment by ernado** [comment]
Most common approach is to handle resumable uploads before cloud, because cloud is used to scale reads, prevent data loss via dublication and other things, that are not needed before the file is fully uploaded/process. On other hand, you will need to handle canceled uploads, and the default way of doing this is not obvious and probably should not be implemented in seaweedfs.

**Comment by brstgt** [comment]
I also think that if your uploads / downloads are so big you need to pause them, you probably should chunk them in your app. I really don't think it is a good way to implement these details in seaweed.

@chrislusf I recommend to close that issue.
