### ISSUE TITLE
How to make file server secure?

### ISSUE THREAD

**Issue by truonguit2010** [chrislusf/seaweedfs#158]
Hi,
I am writing a mobile application, I allow my application write/read file to/from server. But I don't know how to make write operation secure. I want that logged use can do write operation. How can I do that?

Thank you.

**Comment by chrislusf** [comment]
There is a plan to add json web token for write operations, but not ready yet.

**Comment by Davidx7** [comment]
A good alternative would be to serve weedfs content trough a nginx server, limit weedfs to localhost and add authentication to nginx, until @chrislusf adds tokens

**Comment by truonguit2010** [comment]
Thank you. I will consider that @Davidx7 . Are there any config file to config the server?

**Comment by janober** [comment]
You could also have a look at: http://getkong.org (uses under the hood also nginx)

**Comment by mingqlin** [comment]
@chrislusf is json web token  ready?

**Comment by chrislusf** [comment]
Not getting time to finish it yet.

**Comment by jjn2009** [comment]
I'm pretty interested in this as well, it would make using seaweed in production much easier.

**Comment by chrislusf** [comment]
RFC for JWT in SeaweedFS:

Purpose: Volume servers need to ensure the write operations are valid.

Not covered: Securing operations to control Volume server. These should be done via 2-way SSL.

Approach: 
1. When starting master servers and volume servers, they should have a common secret key option.
2. If the secret key is specified, when a client requests a fileId from master server, the master server should also return a JWT, specifying the permission to upload content to a volume server.
2. The volume server should check for JWT for all write operations.

**Comment by krzysztof-kabala** [comment]
+1

**Comment by brstgt** [comment]
Whats the exact purpose?
In MOST cases, end users don't have direct access to vol servers and IMHO they never should. E.g. we use a public API, do a lot of stuff in our backend and as one part of the whole upload process, a file is uploaded to a volserver internally. But there is a lot more to an upload like associating the uploaded file and it's file-id with some other entities like a database entry that stores more metadata or counting stats, checking a sophisticated auth/permission system, sending out notifications and a lot more.
So I don't see many situations where a standalone auth system makes so much sense.
By the way you also could realize that with a redis-based auth in nginx. You can do this in nginx with a few lines of lua and still keep seaweed simple and fast.

**Comment by jjn2009** [comment]
The point of JWT is that the auth is not stand alone, you delegate short lived privileges to clients with short lived tokens via your main application server or some service specifically meant for authentication to other services which may or may not have access to the database with authentication or session information.

All of the actions you describe around metadata associated with files don't get much extra benefit from happening at the server side, theres nothing about the server which makes such an action transactional. At most you prevent the client from interrupting the process by exiting the page mid way for their upload but if you are not keeping close track of these stateful interactions then you are going to have issues regardless, a server can throw an error and cause the exact same issues.

If the service has correct ACLs then there isn't much reason why you would not expose seaweed to the web.

**Comment by brstgt** [comment]
A server is

1. Much less exposed to network errors than a client
2. Is under much better control than a client
3. Can take measure to provide transactional security. A client (today in most cases, mobile clients or browsers) can not or only in a more complicated way.

Of course it depends what you call a client. I'd define anything outside a strictly controlled environment that does not need special authentication.
Do you have a concrete use case for it?

**Comment by chrislusf** [comment]
One setup I was planning is that the master is behind the application servers, but the volume servers are on the wild wide web. The volume servers have the certs to securely talk to the master server. The end user's browser will talk to the app server to get a jwt, and upload the file to the volume server directly.

Will this help your use cases? cc @jjn2009 @krzysztof-kabala @truonguit2010

**Comment by brstgt** [comment]
If there is a real use case for it and @chrislusf does not have the time to implement it, it can still be easily done with nginx (which also adds SSL security to vol servers) and redis (or other fast storage):

- App server request FID from master
- App server generates token and stores it with FID in redis
- Nginx asks redis in lua script and proxies request to vol server or denies access if either token is unknown or does not match FID.
- Nginx could also transparently elect a volume server for a given FID (with volume) in case the previously elected vol server is not available at the moment of upload

**Comment by jjn2009** [comment]
@chrislusf for now any sort of short lived access via jwt for my usecase is significant. There are a number of different ways limits per token could be done, single use + upload limit can allow the issuing application server to easily manage usage limits by just attaching sensible upload file size limit and throttling the number of tokens given per client, this makes client usage upper limits very predictable from the app server side.

I plan on having short timeouts on files uploaded and once metadata is validly committed to the application server via a separate request from the client the app server will update seaweed to keep the file instead of let it expire. I do believe this part is supported by seaweed last I checked. 

Having short lived JWT as a first step would be great though regardless.

**Comment by chrislusf** [comment]
Currently the JWT is implemented for volume servers to check master-issued JWT for writes.

The filer currently does not have plans to support JWT.

**Comment by skurfuerst** [comment]
Hey @chrislusf,

I would love to help on the filer authentication side of things. I currently run seaweedFS in the "secure" fashion (with TLS certificates); and the only thing missing is that I need to keep the unauthenticated Filer HTTP APIs enabled because I want to use S3 (see #2535).

I can think of several possibilities to improve security on the Filer side, and I'd love to contribute to this project. However, I'd need some guidance which of the following approaches (or a totally different one) would be your preferred way to go:

**1. Move S3 proxy to communicate with the Filer over GRPC (#2535)**
- as far as I see this seems very difficult, because GRPC supports not all APIs which the Filer exposes over HTTP (as for the grpc use case, afaics, the clients then directly talk to the volume servers).
- => *seems not feasible*

**2. when S3 and Filer are colocated in the same process, directly call the filer's APIs without exposing them to the outside**
- seems unclean, would maybe involve building "fake" http requests via `httptest`.

**3. protect the Filer API via JWT, and make S3 API generate a JWT and use an Authentication header**
- the JWT would be configured in security.toml
- this would solve my use case
- the JWT would only cover the HTTP API.
- **would be my favourite right now**

**4. implement path-specific permissions**
- I could imagine something like the IAM permissions.
- Unclear for me: How does this extend to the GRPC API?
- possibly way more work.

@chrislusf Am I missing any case? If I created a pull request for 3), would you be willing to look into it?

All the best, and keep up the awesome work for the project,
Sebastian

**Comment by chrislusf** [comment]
Could you please write up a more detailed design for option 3?

**Comment by skurfuerst** [comment]
Hey @chrislusf ,

here we go :)

**3. protect the Filer API via JWT, and make S3 API generate a JWT and use an Authentication header**

- create a new config option in security.toml for the "filer HTTP JWT secret"

- in Filer Handler, check the JWT here: https://github.com/chrislusf/seaweedfs/blob/f2cd753bf9ddfbf1c040c7d21ab3d9f617aec15a/weed/server/filer_server_handlers.go#L14
  - use weed.guard for checking the JWT, similar to https://github.com/chrislusf/seaweedfs/blob/f2cd753bf9ddfbf1c040c7d21ab3d9f617aec15a/weed/server/volume_server_handlers.go#L49
  - or maybe use a method similar to vs.maybeCheckJwtAuthorization (still need to check this): https://github.com/chrislusf/seaweedfs/blob/f2cd753bf9ddfbf1c040c7d21ab3d9f617aec15a/weed/server/volume_server_handlers.go#L112

- In S3 API, generate the JWT and add it as Authorization header, at places like https://github.com/chrislusf/seaweedfs/blob/7210558c7bb6efbd8377975918143478a14c5b3c/weed/s3api/s3api_object_handlers.go#L383
  - generation of the JWT token can be similar to https://github.com/chrislusf/seaweedfs/blob/332d49432dfc5328b803ddbe540704d303500cfd/weed/server/master_server_handlers.go#L152

am I overlooking anything?

All the best,
Sebastian

PS: The code base is really well structured and good to read 👍 👍 👍

**Comment by kmlebedev** [comment]
Maybe you should sync with https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-jwt-authorizer.html ?

**Comment by skurfuerst** [comment]
Hey,

@kmlebedev can you elaborate what you mean with this? I don't understand what you mean :)

All the best,
Sebastian

**Comment by chrislusf** [comment]
Looks good!

**Comment by skurfuerst** [comment]
see #2543 for the PR :)
