### ISSUE TITLE
S3 API - enforce recursive delete

### ISSUE THREAD

**Issue by LazyDBA247-Anyvision** [chrislusf/seaweedfs#1647]
Hi @chrislusf 

https://github.com/chrislusf/seaweedfs/blob/781585b195bee1ef389a48c3303d93200edd7fab/weed/s3api/s3api_object_handlers.go#L116

can we have it configurable by ENV?
in order not to break backward compatibility, maybe have it defaulted to recursive delete, but that's not s3 compatible (s3 delete is only direct, need to do listObjects and send all objects)

10x!

**Comment by LazyDBA247-Anyvision** [comment]
and as far as I understand, each object delete will cause the filer to do "list-objects" which puts unnecessary stress on the DB with ordering results and another "heavy" query.

**Comment by chrislusf** [comment]
the "list-objects" is to check whether the folder with deletion is empty or not. It is added recently https://github.com/chrislusf/seaweedfs/commit/0d345ac97d941bef0991c0cb08632ccf08c0ee83

Here are two related things to consider:
1. folder deletion should be recursive or not.
2. allow empty folder or not.

To follow AWS S3:
1. folder deletion would not make sense since empty folders are auto deleted while non-empty folder deletion would not work.
2. auto delete empty folder.

Not following S3:
1. folder deletion is all recursive.
2. allow empty folder.

I am debating myself also.

**Comment by LazyDBA247-Anyvision** [comment]
I think the best will be to have as close as we can S3 API compatibility, you want your code (AWS s3 SDK) to work the same on SW and the same on AWS S3.
if you an S3 API - for example DeleteObject it should behave the same as the "original".

**Comment by LazyDBA247-Anyvision** [comment]
so:
1. not enabling folder deletion - not s3 compatible
2.about the "empty" folder, can we change the DB realtion/logic so we don't need to create the "folder" row...
example:
when creating a new bucket with 1 file:   /NewBucket/path1/path2/file.txt
there are no rows for path1/path2 as they are "virtual" path..., so when I delete file.txt
there is no path1/path2 to delete :+1:

**Comment by chrislusf** [comment]
> can we change the DB realtion/logic so we don't need to create the "folder" row

It is a nice idea. but this will make it not compatible with other filer metadata. there are other tricks to reduce the "is-directory-emtpy" checking. e.g., save a "check-directory-is-empty-or-not" flag to a random file, and only do the checking when that file is deleted.

**Comment by chrislusf** [comment]
Allowing directory-deletion is different, but better than S3? I did not hear complaints about it before. Why it is not desired?

**Comment by LazyDBA247-Anyvision** [comment]
it is desired, but not as the only option.
need to enable control over it, so you can "enforce" S3 compatibility if you need it.

**Comment by chrislusf** [comment]
move "delete-directory-if-empty" to read time
