### ISSUE TITLE
Lifecycle policy s3

### ISSUE THREAD

**Issue by fixNoobi** [chrislusf/seaweedfs#1798]
**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version : `Centos 7`
- output of `weed version` 2.24
- if using filer, show the content of `filer.toml` - none

**Additional context**
Does Not found wiki page, of  FAQ of using lifecycle policy.
That feature supported now?

**Comment by chrislusf** [comment]
Lifecycle policy is not supported, yet. 

Which feature do you want?

**Comment by fixNoobi** [comment]
Need auto delete files older n-day or n-hour

So may use cronjob with awscli, but it no good idea

**Comment by chrislusf** [comment]
you can use TTL?

**Comment by fixNoobi** [comment]
How can use TTL ? 
We are use minioclient sdk, for java app

**Comment by chrislusf** [comment]
see https://github.com/chrislusf/seaweedfs/wiki/Path-Specific-Configuration#options

**Comment by fixNoobi** [comment]
this apply to all fs?
How use for only one bucket  TTL?

**Comment by chrislusf** [comment]
it is path specific.

**Comment by fixNoobi** [comment]
Can u get sample command?

**Comment by chrislusf** [comment]
How to improve the wiki? I thought it is very obvious.

```
fs.configure -locationPrefix=/some/path -ttl=3d -apply
```

**Comment by ramonmpa** [comment]
Just giving more information because I faced the same challenges.

I'm using seaweedfs as docker container with docker-compose so I have multiple services (one for master, another for s3, volume etc.)

When you are using s3 service the buckets you created will be under /buckets path, as command below show:

`curl -H "Accept: application/json" "http://localhost:8888/?pretty=y"`

```
{
  "Path": "",
  "Entries": [
    {
      "FullPath": "/buckets",
      "Mtime": "2022-10-11T19:21:07Z",
      "Crtime": "2022-10-11T19:21:07Z",
      "Mode": 2147484159,
      "Uid": 0,
      "Gid": 0,
      "Mime": "",
      "TtlSec": 0,
      "UserName": "",
      "GroupNames": null,
      "SymlinkTarget": "",
      "Md5": null,
      "FileSize": 0,
      "Rdev": 0,
      "Inode": 0,
      "Extended": null,
      "HardLinkId": null,
      "HardLinkCounter": 0,
      "Content": null,
      "Remote": null,
      "Quota": 0
    },
... ]
}
```

So to add TTL to a folder created using s3 sdk, your path will be "/buckets/<bucket_name>/<folder_name>"

So to run fs.configure command you need first to access the master container. 

`docker exec -it <master_container_name> /bin/sh`

There you need to run: 

`weed shell`

then 

`fs.configure -locationPrefix=/buckets/bucket1/folder1 -ttl=3m -apply`

In this way, if you create a file under bucket1/folder1 then the file will be deleted after 2 minutes.
