### ISSUE TITLE
why does it limit the volume to 32G, the code looks weird

### ISSUE THREAD

**Issue by ljleader** [chrislusf/seaweedfs#217]
https://github.com/chrislusf/seaweedfs/blob/master/go/storage/store.go#L347

```golang
if MaxPossibleVolumeSize >= v.ContentSize()+uint64(size) {
	size, err = v.write(n)
} else {
	err = fmt.Errorf("Volume Size Limit %d Exceeded! Current size is %d", s.volumeSizeLimit, v.ContentSize())
}
```

we already limit the volume size through master, why there's MaxPossibleVolumeSize? 

another thing is the error message, it uses MaxPossibleVolumeSize in the if condition, but uses s.volumeSizeLimit as the error message

**Comment by chrislusf** [comment]
The MaxPossibleVolumeSize is a hard limit, over which the file read/write would be wrong.

The volume size through master is a soft limit. Due to delays of the reporting for actual volume size, the master may not have accurate volume size, and could possibly send requests to volume that are over the hard limit.
