### ISSUE TITLE
[shell] fs.meta.save with filters by volume server

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#2523]
I do weekly full seaweed backups
from each server volume separately, and before that I make a full backup of metadata via fs.meta.save.
With the increase in the number of volume servers, it has become expensive to do a full metadata backup; I want to make a metadata backup that belongs only to a specific volume server

**Comment by chrislusf** [comment]
`fs.meta.save` supports save for a particular folder. It does not know any particular volume server though since they are logically separate: one for blob storage and the other for filer storage. There are no good way to just backup file system metadata for one volume server.

If you have any suggestions, please let me know.

```
> fs.meta.save -h
Usage of fs.meta.save:
  -o string
    	output the meta data to this file
  -obfuscate
    	obfuscate the file names
  -v	print out each processed files

> help fs.meta.save
  fs.meta.save	# save all directory and file meta data to a local file for metadata backup.

	fs.meta.save /               # save from the root
	fs.meta.save -v -o t.meta /  # save from the root, output to t.meta file.
	fs.meta.save /path/to/save   # save from the directory /path/to/save
	fs.meta.save .               # save from current directory
	fs.meta.save                 # save from current directory

	The meta data will be saved into a local <filer_host>-<port>-<time>.meta file.
	These meta data can be later loaded by fs.meta.load command

```
