### ISSUE TITLE
Should the S3 proxy communicate with Filer over gRPC instead of HTTP?

### ISSUE THREAD

**Issue by skurfuerst** [chrislusf/seaweedfs#2535]
Hello Seaweedfs-Team,

THANKS for an awesome project and for your great work!

**Describe the bug**

Should the S3 proxy communicate with Filer over gRPC instead of HTTP?

I am running filer with `-disableHttp`, as it is described on https://github.com/chrislusf/seaweedfs/wiki/Security-Overview. As far as I understand the code, the S3 connector tries to connect to Filer over HTTP (f.e. [here](https://github.com/chrislusf/seaweedfs/blob/master/weed/s3api/s3api_object_copy_handlers.go#L72).

This errors, as Filer is not active over HTTP due to `-disableHttp`.

**Expected behavior**

Is there any reason that S3 does not connect to  Filer via GRPC, because then, it would be authenticated?

In case you think that is a good idea, I can try to provide a patch.

All the best, and happy holidays,
Sebastian

**Comment by chrislusf** [comment]
S3 upload is refusing filer http upload logic. Changing to gRPC would be a huge project.

**Comment by skurfuerst** [comment]
Thanks for letting me know, then I'll close this issue I guess. I'll think about whether I'll find another solution :)

**Comment by Samy060** [comment]
@skurfuerst 
Hey there..I need some help since you are pretty active here...:)
Can you please explain how can we implement TLS for seaweedfs master and S3 ..saw you mentioned you are running seaweedfs with TLS enabled in one of the thread! We are totally stuck trying to achieve it since 2 weeks. Please help us

Please refer my query below for the full context:
https://github.com/seaweedfs/seaweedfs/issues/5970

Basically we are using openshift cluster, having hashicorp vault as Certificate Authority. Vault agent injector will inject the certificates and keys to the pods that needs TLS enabled. So here also the same case we have configured the vault agent injector to inject certs and keys at required path inside container.
In our case 
/etc/seaweedfs/server.crt
/etc/seaweedfs/server.key
/etc/seaweedfs/ca.crt
/etc/seaweedfs/security.toml

Here is my master's statefulset that I configured.

 apiVersion: apps/v1
 kind: StatefulSet
 metadata:
   name: seaweedfs-master
   namespace: {{ .Release.Namespace }}
 spec:
   serviceName: seaweedfs-master
   replicas: {{ .Values.master.replicas }}
   selector:
     matchLabels:
       app: seaweedfs-master
   template:
     metadata:
       labels:
         app: seaweedfs-master
       annotations:
         vault.hashicorp.com/agent-inject: "true"
         vault.hashicorp.com/agent-inject-status: 'update'
         vault.hashicorp.com/role: "seaweedfs-role"
         
         # Inject security.toml without pulling from seaweedfs-secrets
         vault.hashicorp.com/agent-inject-template-security.toml: |
           [grpc]
           ca = "/etc/seaweedfs/ca.crt"
 
           [grpc.master]
           cert = "/etc/seaweedfs/server.crt"
           key  = "/etc/seaweedfs/server.key"
 
         vault.hashicorp.com/agent-inject-path-security.toml: "/etc/seaweedfs/security.toml"
         
         # Server Key Injection
         vault.hashicorp.com/agent-inject-secret-server.key: "pki/issue/vault-local"
         vault.hashicorp.com/agent-inject-template-server.key: |
           {{`{{- with secret "pki/issue/vault-local" "common_name=master.seaweedfs-system.svc.cluster.local" -}}
           {{ .Data.private_key }}
           {{- end }}`}}
         vault.hashicorp.com/agent-inject-path-server.key: "/etc/seaweedfs/server.key"
         
         # Server Certificate Injection
         vault.hashicorp.com/agent-inject-secret-server.crt: "pki/issue/vault-local"
         vault.hashicorp.com/agent-inject-template-server.crt: |
           {{`{{- with secret "pki/issue/vault-local" "common_name=master.seaweedfs-system.svc.cluster.local" -}}
           {{ .Data.certificate }}
           {{- end }}`}}
         vault.hashicorp.com/agent-inject-path-server.crt: "/etc/seaweedfs/server.crt"
         
         # CA Certificate Injection
         vault.hashicorp.com/agent-inject-secret-ca.crt: "pki/issue/vault-local"
         vault.hashicorp.com/agent-inject-template-ca.crt: |
           {{`{{- with secret "pki/issue/vault-local" "common_name=master.seaweedfs-system.svc.cluster.local" -}}
           {{ .Data.issuing_ca }}
           {{- end }}`}}
         vault.hashicorp.com/agent-inject-path-ca.crt: "/etc/seaweedfs/ca.crt"
 
         # Set the injection path for all secrets
         vault.hashicorp.com/secret-volume-path: "/etc/seaweedfs/"
     spec:
       serviceAccountName: {{ .Values.serviceAccount.name }}
       containers:
       - name: seaweedfs-master
         image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
         args:
           - "master"
           - "-ip"
           - "$(POD_IP)"
           - "-mdir"
           - "/data"
           - "-volumeSizeLimitMB"
           - "100"
         env:
         - name: POD_IP
           valueFrom:
             fieldRef:
               fieldPath: status.podIP
         - name: TLS_CERT
           value: {{ .Values.tls.certPath }}
         - name: TLS_KEY
           value: {{ .Values.tls.keyPath }}
         - name: TLS_CA
           value: {{ .Values.tls.caPath }}
         volumeMounts:
         - name: master-storage
           mountPath: /data
         ports:
         - containerPort: 9333
   volumeClaimTemplates:
   - metadata:
       name: master-storage
     spec:
       accessModes: [ "ReadWriteOnce" ]
       resources:
         requests:
           storage: {{ .Values.master.storage }}
       storageClassName: {{ .Values.storageClassName }}
 {{- end }}


Even after injecting certs, keys and security.toml file at /etc/seaweedfs/  when we try to curl the seaweedfs pod from internally, it's not TLS enabled 

Please help :
* How can we enable TLS for seaweedfs master and s3
* Also how we can validate if it is TLS enabled
* Please check if below security.toml is correct or not. Let me what more needs to configured here
security.toml: |
           [grpc]
           ca = "/etc/seaweedfs/ca.crt"
 
           [grpc.master]
           cert = "/etc/seaweedfs/server.crt"
           key  = "/etc/seaweedfs/server.key

* Let me if know if I'm doing anything wrong here since this is very new things for me.
Thanks.. awaiting for your reply
