### ISSUE TITLE
seaweedfs 2.84 - volume.fsck -reallyDeleteFromVolume errors rather than warns on all readonly volumes

### ISSUE THREAD

**Issue by Radtoo** [chrislusf/seaweedfs#2562]
If you have a few hundred or a few thousand volumes and try to use "volume.fsck -reallyDeleteFromVolume", you'll get a whole lot of errors due to the readonly volumes, each of them interrupting the process.

I believe this command should only warn about the readonly volumes and continue, not error and abort. It even seems like the command does nothing if it errors. so deleting data not referenced by the filer is maybe currently not possible unless absolutely all volumes are read/write.

Additionally I thought it'd maybe be nice to have a parameter to allow temporarily marking volumes as read/write for the purpose of running this command, so that it runs smoothly and the volumes automatically can return to being readonly in setups where this is desired.

**Comment by chrislusf** [comment]
Added a fix to skip read only volumes.

**Comment by timothywcrane** [comment]
> Added a fix to skip read only volumes.

Thank your fixing it this way even if out of expediency. 

I actually appreciate the allowance of reads to take a front seat to writes any time... by default at least. I see it as a feature and not a bug. If the maintainer knows I error in this as a fact, please chime in.

If anything is to ever be blocking in today's workflows... let the writes stand to the side while the client gets what already exists in the lake. This allows for async/sync decoupling, as in reality there is no simply choosing one over the other. 

As long as you have reads and writes holding different latencies for the same workload you have sync context to deal with in some way. Projects like this one allow for use case cures for these issues instead of another symptomatic medicinal coverup (insert framework here) on the front... 

Thank you Chris.

BTW, anyone spitting seeds into beds of SeaweedFS with RedPanda?
