### ISSUE TITLE
Support Multipart Upload feature

### ISSUE THREAD

**Issue by Wen777** [chrislusf/seaweedfs#258]
### WHAT / WHY

Thanks all contributor effort, I do really like this project.

I have question about do there have any plane to support multipart upload feature for big file ?
### Reference:

https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingRESTAPImpUpload.html

**Comment by chrislusf** [comment]
We have support for large file uploads, which will be split into chunks and uploaded separately. The list of chunks are stored in a manifest file and handled transparently when downloading.

Does this solve your problem?

@tnextday do you want to work on this since you have worked on https://github.com/chrislusf/seaweedfs/pull/224 already?

**Comment by tnextday** [comment]
Sorry, i'm working on some other feature.

**Comment by Wen777** [comment]
@chrislusf I am happy to hear this news. Where I can find this feature's rest api ? I already checked wiki and didn't find any related thing. 

I read #224. It seems that doesn't exit this api right ? It would be good if any one can give advise how to implement this feature. I'm glade to do this.

Thanks.

**Comment by chrislusf** [comment]
this is already supported.
