### ISSUE TITLE
Don't bring politics to SeaweedFS

### ISSUE THREAD

**Issue by sryio** [chrislusf/seaweedfs#2726]
I feel so sad you bring politics to SeaweedFS. Open source project should not be involved in any politics and should be neutral

**Comment by EsqerYasen** [comment]
anti war is not about politics , its about humanity.

**Comment by sryio** [comment]
> anti war is not about politics , its about humanity.

I think you know nothing about "humanity".

**Comment by chrislusf** [comment]
One of my colleagues is a Ukrainian. He is defending his country now. I want him back safely.

**Comment by nkosi23** [comment]
@chrislusf the issue is that users of SeaweedFS may be russians, or even Europeans, Americans, Latin American and Indian agreeing with Russia's arguments (and there are many of them). 

Also keep in mind that some users and contributors may live or have family living in countries torn by war for years and not receiving any mainstream media coverage in the world. This is for example my case, in the country where my parents originate (and vast part of my family lives) whole villages are attacked by night or by day and burned up daily, people are killed by the dozens daily, women raped in front of their family (sometimes sons are forced to rape their own mother). Folks are mutilated with machetes. This has being going on for decades with zero mainstream media coverage, yet everybody knows which countries benefit from this situation. And I'm pretty sure that many people here are affected by similar conflicts putting the lives of their family at risk and wished there was stronger media exposure. 

But we do not bring it in IT open-source projects, forums and mailing lists, this is not the way to go. We all do the effort of keeping politics out of the discussion despite sometimes having such strong political causes to support. My point it is, it may look sort of rude and maybe even somehow disrespectful to drag (and taint) all this community with your political view as soon as you are personally affected. So now, if I run SeaweedFS people may understand that I do so because I support Ukraine, including any Russian customers I may have.

Maybe a separate website could be setup to allow SeaweedFS users wanting to support Ukraine to do so. If supporting peace is the goal, there is a way to support peace in a neutral way, for example calling the latest release: "Peace in Ukraine" or better "Peace in the World" would have been neutral. "Stand with Ukraine" is not anti-war, it is actively taking side on a very hot political issue. Especially since many people consider that Ukraine has been waging war on Russian minorities since 2014, I have seen reports saying that over 10,000 russians civilians have been killed since 2014 which supposedly partially motivated Russia's actions - compared to about 300 Ukrainians civilians killed since the beginning of the invasion or special operation - however you want to call it. Whether it's true or not, the fact is many people believe it, so my point is that "Standing with Ukraine" cannot and will not be understood as an universal message for peace. 

If SeaweedFS is taking sides, maybe you will start blacklisting Russian hostnames in the official repo if the conflict intensifies? In addition to forcing political views on people who may disagree with you, this is the kind of questions and uncertainty that such political activism opens up. Even this is not your intent right now, people may start piling up with activism in an irrational manner once that door is opened, to the point that you will be forced to act "if you are a true friend of Ukraine and a defender of peace". Also If a Russian person wanted to contribute he may not feel welcome here. i'll stop here but there are so many issues with this approach.

I understand how you feel about your friend but please do not do this, this is not the right approach. Despite the pain let your emotions come down and keep acting rationally. And keep in mind that the official war narrative on this conflict may change anytime, so you may end up being embarrassed by this activism down the line. What looks like a risk-free universal mainstream cancel movement today may end up being being a marginalized activist speech tomorrow.  

I am personally not mad at you for this (even though I feel that this project should not be politicized), I just wanted to try to explain how others may perceive this move. I hope this comment does not come as rude as this is not my mindset, I say this with a constructive and very friendly mindset. Any disagreement we may have will not be able to overshadow how grateful I am for the work you have put in SeaweedFS, so I hope our relationship can be focused on that. Bringing together Russian, Ukrainians, Americans and Europeans to use and collaborate peacefully around the SeaweedFS project is a much more meaningful act of peace than taking part in political agitation.

**Comment by flomo29** [comment]
@nkosi23 You can't really be neutral! It's like witnessing a fight and not doing anything. You don't even call the police or help and you accept that the victim dies or is seriously injured. It is important to remember that the victim was not the attacker and that the attacker hit the other person for no reason. And if a Pro Russian contributor feels offended and has nothing more to contribute, then chrislusf certainly won't miss him. People have values, should have values. There is no reason anywhere in this day and age to start a war. If there is a war somewhere, you don't have to take sides, but you should be against war in general. You know that Putin is displaying dictatorial behavior. There is no valid reason for a war against Ukraine. Showing approval for Ukraine is approval for peace these days.
