### ISSUE TITLE
Leader panic / volumes unwritable / recovery strategy

### ISSUE THREAD

**Issue by markschmid** [chrislusf/seaweedfs#278]
While seaweed seems to run fine for the most part, we've run into the following two (not necessarily related) error conditions:

`I0321 13:45:45 23008 volume_layout.go:157] Volume 1 becomes unwritable` (the same for the other 6 volumes)

and

`panic: assertion failed: leader.elected.at.same.term`

The only working recovery was to erase the mdir and the volume dir (losing the data).

Our questions:
1) What's causing these situations (and how to prevent them)?
2) Is there a recovery strategy without data loss?
3) Any suggestions in regards to our setup below (e.g. since we only have 1 master, we don't really need seaweed to elect a leader (-> 2nd error message)), are we starting the master/volume server correctly?

Any help greatly appreciated!

Our setup is using seaweed with 2 hosts, like this:

Host A runs 1 master and 1 volume server:
`$GOPATH/bin/weed -logtostderr master -mdir="/mydir/master" -port=9333 &> /mylogdir/logs/weedfs_master.log`
`$GOPATH/bin/weed -logtostderr volume -dir="/mydir/8080" -mserver=localhost:9333 -port=8080 -ip=<myip> &> /mylogdir/logs/weedfs_volume.log`

Host B runs 1 volume server
`$GOPATH/bin/weed -logtostderr volume -dir="/mydir/8080" -mserver=<ip of Host A>:9333 -port=8080 -ip=<myip> &> /mylogdir/logs/weedfs_volume.log`

**Comment by chrislusf** [comment]
1) What's causing these situations (and how to prevent them)?
Do not know. It could be network slowness, volume become full, etc. Need to see the logs.

2) Is there a recovery strategy without data loss?
Yes. You can recover all data just from the volumes. For your second error, just erase mdir should be fine.

3) Any suggestions in regards to our setup below (e.g. since we only have 1 master, we don't really need seaweed to elect a leader (-> 2nd error message)), are we starting the master/volume server correctly?
The setup is fine. Need to know how many files, how is the network, usage pattern.

**Comment by markschmid** [comment]
OK, thanks. Unfortunately, the logs have been overwritten. We'll keep watching the situation.

> Yes. You can recover all data just from the volumes.
How would that work exactly? Is there some documentation on how to do that?
If in production we run into the situation where volumes become unwritable, we need to know how to get that volume server running again without losing the data in the volume dirs.

**Comment by chrislusf** [comment]
I think you may be using 0.70beta version, which I released about one year ago. Please use the 0.70 version released a few days ago.

All the volume .dat files should be exactly the same. If one of the copies are lost, just duplicate one on some other machine.
