### ISSUE TITLE
how to monitor seaweedfs

### ISSUE THREAD

**Issue by jeromeheng** [chrislusf/seaweedfs#534]
hi @chrislusf 
      If I use seaweedfs，how could I monitor it ，and how to use  monitor api。

**Comment by ijunaid8989** [comment]
Hello @jeromeheng bet way is to create a service (Ubuntu 16.04), an upstart job(14.04) or anything in windows(service), to start and stop seaweedFS, and select a place where are you going to save the all log files, which will be created while service/job..

In upstart job all the logs are in var/logs/upstart/ something..

The very last step is to get these logs into use, we are using sumoCollector for this, 

You simply signup on Sumo Logic and then install its sumoCollector to your OS, and in the configuration of that collector, give the path of your log files, That way you can have all those logs files showing in sumoLogic, then you do many many things on that data, 

for example, searching a specific vacuum, a request, or you can even schedule a search that if this comes in logs "abc" then send me email. like that..

There are many more ways, in case you want help or ask am all ears..

**Comment by ijunaid8989** [comment]
Or you can monitor your ports if you want the most minimal monitoring.. 

using nagios, uptime robot or any other tool, just monitor the filer port, master port or any other port you want to monitor.

**Comment by jeromeheng** [comment]
@ijunaid8989 
thanks
By the way ，how to start&stop seaweedfs cluster，just like start-all.sh& stop-all.sh about hbase and so on。

**Comment by ijunaid8989** [comment]
Sorry I have no idea about cluster.

@chrislufs may have an answer to that.

**Comment by jeromeheng** [comment]
@chrislusf 
how to start & stop  quickly ?

**Comment by ijunaid8989** [comment]
@jeromeheng The best way is to add

Upstart job if you are using Ubuntu 14.04
Service if you are on higher version of ubuntu
or on windows.

the best way is to create a service for it to start and stop it in a manner, this way you can also see the logs in a specific directory.

**Comment by phal0r** [comment]
Are there plans to support a Prometheus Exporter for Monitoring?

**Comment by chrislusf** [comment]
Pull Requests are welcome.

**Comment by rockiee281** [comment]
we crawl weed rest api by  collectd + python scripts for metirces,  and  graphite + grafana  as monitor dashboard

**Comment by lastsky** [comment]
1. install telegraf 
2. see https://github.com/influxdata/telegraf/tree/master/plugins/inputs/httpjson
3. see https://github.com/influxdata/telegraf/tree/master/plugins/outputs/prometheus_client
4. see https://github.com/chrislusf/seaweedfs/wiki/Master-Server-API#check-system-status
5. send native seaweedfs metrics to prometheus with telegraf

p.s. grafana dashboards for seaweedfs are awesome!

you don't need especial exporters because there are no interface for them in seaweedfs. i think they could slow seaweedfs down. just take statistics from http json.

![screen shot 2017-09-26 at 16 11 08](https://user-images.githubusercontent.com/334280/30879176-1d47a31c-a318-11e7-9b47-9a1b7528228c.jpg)
![screen shot 2017-09-26 at 16 28 38](https://user-images.githubusercontent.com/334280/30879188-24abc714-a318-11e7-9757-d6b866e6bd8f.jpg)
![screen shot 2017-09-26 at 06 29 36](https://user-images.githubusercontent.com/334280/30879199-2dd3ce0e-a318-11e7-933a-4ed24ab961a4.jpg)
![screen shot 2017-09-26 at 06 29 31](https://user-images.githubusercontent.com/334280/30879206-303826d6-a318-11e7-8647-d211b6d99e59.jpg)

and so on.

**Comment by chrislusf** [comment]
@lastsky this is very helpful! Thanks!

btw: why there are so many volumes?

**Comment by craveica** [comment]
@lastsky Can you share your grafana dashboard? It looks pretty nice.

**Comment by rockiee281** [comment]
@lastsky Your dashboard is awesome, will you share it ?

**Comment by lastsky** [comment]
We were working on some integrations with seaweedfs and I'm afraid only 10% metrics is actually available from seaweedfs, other 90% we wrote for app. So my dashboard will be actually useless without production code.

I will think about how to implement clean install with ansible and deploy standart dashboard to grafana. But now this moment I actually have no answer. Sorry for late response, that's because I have no answer.

**Comment by lastsky** [comment]
(it's 1/10 of all dashboard, looks really poor)

**Comment by chrislusf** [comment]
see https://github.com/chrislusf/seaweedfs/wiki/System-Metrics

**Comment by chongweihe** [comment]
Hi, I read your answers, but I didn't implement Grafana+Prometheus to monitor seaweedfs, is there another way?
