### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by franquis** [chrislusf/seaweedfs#717]
Hi,
When starting SeaweedFS using pre-built binary (**v0.94 linux_386**) on _Ubuntu Xenial_, it ends with an `invalid memory address or nil pointer dereference` error.

**Describe the bug**
```
$ weed server -dir=/data

I0829 12:37:52  9413 file_util.go:20] Folder /data Permission: -rwxr-xr-x
I0829 12:37:52  9413 file_util.go:20] Folder /data Permission: -rwxr-xr-x
I0829 12:37:52  9413 master_server.go:68] Volume Size Limit is 30000 MB
I0829 12:37:52  9413 server.go:186] Start Seaweed Master 0.94 at localhost:9333
I0829 12:37:52  9413 raft_server.go:47] Starting RaftServer with localhost:9333
I0829 12:37:52  9413 raft_server.go:51] Peers Change: [] => []
I0829 12:37:54  9413 raft_server.go:75] Initializing new cluster
I0829 12:37:54  9413 raft_server.go:83] raft: Has been stopped
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xc0f163]

goroutine 25 [running]:
github.com/chrislusf/seaweedfs/weed/server.(*MasterServer).SetRaftServer(0xc0001dab40, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/master_server.go:95 +0x43
github.com/chrislusf/seaweedfs/weed/command.runServer.func2.1(0xc000192af0, 0xc000263dc0, 0xc0001dab40, 0xc000192b00)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/server.go:197 +0x10c
created by github.com/chrislusf/seaweedfs/weed/command.runServer.func2
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/server.go:192 +0x407

```

**System Setup**
`$ weed server -dir=/data`

**Expected behavior**
Expecting `seaweed` to start properly 😊

**Additional context**
```
OS:                    Ubuntu 16.04.4 LTS
Kernel:                4.4.0-1049-aws
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
Stepping:              2
CPU MHz:               2400.038
BogoMIPS:              4800.07
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0,1
```

**Comment by chrislusf** [comment]
This seems some goroutine timing issue. Is this always reproducible?

**Comment by franquis** [comment]
Yes, got this error everytime I start weed

**Comment by franquis** [comment]
Same problem with amd64 v0.94

**Comment by chrislusf** [comment]
ok. Need details on how to reproduce this, especially how to get a ubuntu instance like yours.

**Comment by tomi-engel** [comment]
Hi,

I have seen the same behavior when running the latest Seaweed (1.12) on Fedora 29 Silverblue inside a container:

```
[root@korora-01 data]# podman start -a -i seaweed-m01
I1221 20:00:08     1 file_util.go:19] Folder /data Permission: -rwxr-xr-x
I1221 20:00:08     1 master_server.go:68] Volume Size Limit is 10 MB
I1221 20:00:08     1 master.go:80] Start Seaweed Master 1.12 at 0.0.0.0:9333
I1221 20:00:08     1 raft_server.go:47] Starting RaftServer with 10.88.0.18:9333
I1221 20:00:08     1 raft_server.go:51] Peers Change: [] => []
I1221 20:00:10     1 raft_server.go:75] Initializing new cluster
I1221 20:00:10     1 raft_server.go:83] raft: Has been stopped
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xe38743]

goroutine 13 [running]:
github.com/chrislusf/seaweedfs/weed/server.(*MasterServer).SetRaftServer(0xc000260c60, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/master_server.go:94 +0x43
github.com/chrislusf/seaweedfs/weed/command.runMaster.func1(0xc000186240, 0xc000260c60)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/master.go:91 +0xfe
created by github.com/chrislusf/seaweedfs/weed/command.runMaster
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/master.go:87 +0x444
```

... and after a lot of head scratching it turned out that the solution was to please SELinux and add the "z" option to the volume binding of the container:

```
podman create -v /var/zones/seaweed-v01/data:/data:z --hostname ...
```

I "think" this is because the data folder actually is "visible" to Seaweed with a "writeable" flag ... but any write will actually fail. I did not debug the code ... but that would be my "best guess". Maybe there is an easy way to detect that if file creation fails in a weird way.

**Comment by chrislusf** [comment]
@tomi-engel Thanks a lot! Having no knowledge about podman, I would never have thought of this!

https://github.com/containers/libpod/blob/master/docs/podman-build.1.md

"The z option tells podman that two containers share the volume content. As a result, podman labels the content with a shared content label. Shared volume labels allow all containers to read/write content. "

**Comment by tomi-engel** [comment]
"podman" is basically the Fedora "docker" drop-in-replacement. Since the issue seems to be related to file permissions I guess it is a "generic" (SELinux?) issue.

@franquis has "Xen" and "aws" in his system description ... so it seems to me like his Ubuntu 16.04.4 is not running on bare metal … and I suspect AWS has some "security layer" in place as well (maybe SELinux too).

But the real question is … how to detect that and "fail gracefully" with a well defined error message.

I am not really familiar with the Seaweed code base ... but I suspect an "easy" fix might be to enhance the `TestFolderWritable` function in the `file_util.go`module. 
Maybe one could simply create a temporary file with a random name in that folder to proof that it is really writeable. 

The "pure" solution might be to include a dedicated SELinux library like [https://selinuxproject.org/page/NB_Userspace_Libraries](url) ... but I would suspect that this might be too much effort.

There might also be some places in the seaweed code where file creation errors are not checked.
However, it seems like the specific crash from our logs is related to the "raft server" part

```
weed/command/master.go
..
		raftServer := weed_server.NewRaftServer(r, peers, myMasterAddress, *metaFolder, ms.Topo, *mpulse)
		ms.SetRaftServer(raftServer)
..
```

so it seems like `weed_server.NewRaftServer` is returning a nil object. So perhaps 

- `ms.SetRaftServer`should fail gracefully when getting a "nil" argument.
- `weed_server.NewRaftServer` needs to check for the "ACL write permission" stuff

I hope this is helpful.

**Comment by chrislusf** [comment]
added error handling for this case.

**Comment by dzang** [comment]
hi @chrislusf , I have the same problem with filer on an centos 7.5,x86_64 server.
I0810 09:30:20 50306 filer_server_handlers_read.go:110] retrieving from http://10.1.1.9:8083/358,1cefad72b0d58766
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x5ddc4f]

goroutine 1891459290 [running]:
bufio.(*Writer).Available(...)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/bufio/bufio.go:607
bufio.(*Writer).WriteString(0x0, 0x18c2de7, 0x19, 0x10100c00ecbd498, 0x0, 0x8000)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/bufio/bufio.go:688 +0x7f
net/http.(*expectContinueReader).Read(0xc00905c1e0, 0xc00a722000, 0x8000, 0x8000, 0xc0130e2c20, 0x44409c, 0x8000)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/http/server.go:890 +0x13b
net/http.transferBodyReader.Read(0xc00eb29cc0, 0xc00a722000, 0x8000, 0x8000, 0x0, 0x2a19e00, 0xc011385ea8)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/http/transfer.go:62 +0x56
io.copyBuffer(0x7f97ebea0388, 0xc00f992df0, 0x1bd4440, 0xc00eb29cc0, 0xc00a722000, 0x8000, 0x8000, 0x3, 0x1, 0xc0130e2d01)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/io/io.go:402 +0x122
io.Copy(...)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/io/io.go:364
net/http.(*transferWriter).writeBody(0xc00eb29cc0, 0x1bce700, 0xc0101f65c0, 0x2, 0x2)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/http/transfer.go:358 +0x16b
net/http.(*Request).write(0xc004719500, 0x1bce700, 0xc0101f65c0, 0x0, 0x0, 0xc00cf8d280, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/http/request.go:655 +0x721
net/http.(*persistConn).writeLoop(0xc00003d320)
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/http/transport.go:1979 +0x1b8
created by net/http.(*Transport).dialConn
        /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/http/transport.go:1358 +0xb0d

**Comment by chrislusf** [comment]
@dzang your logs are totally different. please create a separate issue with details.
