### ISSUE TITLE
Filer 文件和文件夹  同名的问题

### ISSUE THREAD

**Issue by 330570902** [chrislusf/seaweedfs#777]
作者您好：
        我使用的weaweedfs 版本为 0.94 .  Filer 服务使用Cassandra 存储元数据。我在存储文件时发现，与文件名相同的文件夹会被覆盖，反之亦然。请问这是一个BUG 还是在使用Cassandra作为元数据存储时的 feature?

**Comment by chrisluuber** [comment]
It is designed this way.

**Comment by 330570902** [comment]
OK  thank you.

**Comment by chrisluuber** [comment]
Added a fix for this, to report as error if a directory and a file conflict.

**Comment by ijunaid8989** [comment]
there could be a possibility that due to this change https://github.com/chrislusf/seaweedfs/commit/ceca078acb8607f5d3252356617cf630ff6b4be8 , seaweedfs is not saving at same file name? 

we have almost 644 such paths `http://IP:8888/testv-cxnfz/snapshots/thumbnail.jpg`

where post request is coming back with 201. each time. 

```
%HTTPoison.Response{
  body: "{\"size\":121926,\"fid\":\"1278,0fe5e1eb9e303ec5\",\"url\":\"http://ip:8080/1278,0fe5e1eb9e303ec5\"}",
  headers: [
    {"Content-Type", "application/json"},
    {"Etag", "\"e4c15e1d\""},
    {"Date", "Mon, 03 Dec 2018 12:33:03 GMT"},
    {"Content-Length", "101"}
  ],
  request_url: "http://ip:8888/evercam-office/snapshots/thumbnail.jpg",
  status_code: 201
}
```

![image](https://user-images.githubusercontent.com/13561999/49421623-899ff100-f7b2-11e8-8fd3-abe0da23418e.png)
But as you can see this file is only 0B. and it doesn't even open. but sometimes, It gets open for another thumbnail and it shows not the updated one but the very first ever thumbnail was saved on the server, on 1 November when we first moved to version 0.99, right we are on the latest version 1.10.

![image](https://user-images.githubusercontent.com/13561999/49422088-3890fc80-f7b4-11e8-8c3c-6a6fbb75900b.png)
